FROM ubuntu:18.04
MAINTAINER Artem Svetlov <trolleway@yandex.ru>
RUN apt-get install -y osmctools wget

#quick use download files from repo
RUN wget https://raw.githubusercontent.com/trolleway/osm-scripts/master/osmupdate/area.poly
RUN wget https://raw.githubusercontent.com/trolleway/osm-scripts/master/osmupdate/update_dump.py
